import { Task, Project, User } from '@/types/index';

export const mockUser: User = {
  id: 'u1',
  name: 'Alex Morgan',
  email: 'alex@intentflow.ai',
  avatar: 'AM',
};

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Review Q1 product roadmap and send feedback to team',
    description: 'Go through the roadmap doc shared by Sarah and add comments before the all-hands.',
    dueDate: 'Today',
    dueTime: '2:00 PM',
    priority: 'urgent',
    category: 'Work',
    status: 'active',
    subtasks: [
      { id: 's1', title: 'Read the roadmap doc', completed: true },
      { id: 's2', title: 'Add inline comments', completed: false },
      { id: 's3', title: 'Send summary email', completed: false },
    ],
    people: ['SM', 'JD'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 't2',
    title: 'Call John about contract renewal',
    description: 'Discuss the new terms and pricing before the deadline.',
    dueDate: 'Today',
    dueTime: '3:00 PM',
    priority: 'high',
    category: 'Work',
    status: 'active',
    subtasks: [],
    people: ['JD'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 't3',
    title: 'Morning workout — chest & shoulders',
    dueDate: 'Today',
    dueTime: '7:00 AM',
    priority: 'medium',
    category: 'Health',
    status: 'completed',
    subtasks: [
      { id: 's4', title: 'Warm up 10 mins', completed: true },
      { id: 's5', title: '4 sets bench press', completed: true },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 't4',
    title: 'Submit expense report for February',
    dueDate: 'Tomorrow',
    priority: 'medium',
    category: 'Finance',
    status: 'pending',
    subtasks: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 't5',
    title: 'Read "Deep Work" — Chapter 4',
    dueDate: 'This week',
    priority: 'low',
    category: 'Learning',
    status: 'active',
    subtasks: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 't6',
    title: 'Grocery shopping — prepare for dinner party',
    dueDate: 'Today',
    dueTime: '5:00 PM',
    priority: 'high',
    category: 'Personal',
    status: 'active',
    subtasks: [
      { id: 's6', title: 'Wine & cheese', completed: false },
      { id: 's7', title: 'Pasta ingredients', completed: false },
      { id: 's8', title: 'Dessert', completed: false },
    ],
    createdAt: new Date().toISOString(),
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'IntentFlow MVP Launch',
    color: '#3B82F6',
    tasks: 24,
    completed: 18,
    overdue: 1,
    members: ['AM', 'JD', 'SM'],
    dueDate: 'Mar 31',
    progress: 75,
  },
  {
    id: 'p2',
    name: 'Q1 Marketing Campaign',
    color: '#8B5CF6',
    tasks: 16,
    completed: 8,
    overdue: 2,
    members: ['RL', 'KC'],
    dueDate: 'Apr 15',
    progress: 50,
  },
  {
    id: 'p3',
    name: 'Personal Fitness Goals',
    color: '#10B981',
    tasks: 10,
    completed: 6,
    overdue: 0,
    members: ['AM'],
    dueDate: 'Ongoing',
    progress: 60,
  },
];
